//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessConnectManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessCooperationCategory
    {
        public int ID { get; set; }
        public string Business_ID { get; set; }
        public int CooperationCategories_ID { get; set; }
    
        public virtual BusinessUser BusinessUser { get; set; }
        public virtual CooperationCategory CooperationCategory { get; set; }
    }
}
