//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessConnectManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class BusinessUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BusinessUser()
        {
            this.BusinessCooperationCategories = new HashSet<BusinessCooperationCategory>();
            this.InternshipResults = new HashSet<InternshipResult>();
            this.MOUs = new HashSet<MOU>();
            this.Posts = new HashSet<Post>();
            this.Registrations = new HashSet<Registration>();
        }

        public int ID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> Last_Access { get; set; }
        public Nullable<int> Status_ID { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập tên doanh nghiệp.")]
        [RegularExpression(@"^.*\S.*$", ErrorMessage = "Vui lòng nhập tên doanh nghiệp.")]
        public string BusinessName { get; set; }
        public string Address { get; set; }
        public string BusinessPhone { get; set; }
        public string Website { get; set; }
        public string Fanpage { get; set; }
        public string BusinessLogo { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập tên người liên hệ.")]
        [RegularExpression(@"^.*\S.*$", ErrorMessage = "Vui lòng nhập tên người liên hệ.")]
        public string ContactName { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập số điện thoại người liên hệ.")]
        [DataType(DataType.PhoneNumber)]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$|[0-9]{11}", ErrorMessage = "Số điện thoại này không hợp lệ.")]
        public string ContactPhone_1 { get; set; }
        public string ContactPhone_2 { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập email người liên hệ.")]
        [RegularExpression("^[a-zA-Z0-9_\\.-]+@([a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}$", ErrorMessage = "E-mail không hợp lệ.")]
        [EmailAddress(ErrorMessage = "E-mail không hợp lệ.")]
        public string EmailContact { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BusinessCooperationCategory> BusinessCooperationCategories { get; set; }
        public virtual Status Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InternshipResult> InternshipResults { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MOU> MOUs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Post> Posts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Registration> Registrations { get; set; }
    }
}
