//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessConnectManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CooperationCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CooperationCategory()
        {
            this.BusinessCooperationCategories = new HashSet<BusinessCooperationCategory>();
        }
    
        public int ID { get; set; }
        public string CooperationCategoriesName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BusinessCooperationCategory> BusinessCooperationCategories { get; set; }
    }
}
