//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessConnectManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InternshipResult
    {
        public int ID { get; set; }
        public string Student_Email { get; set; }
        public Nullable<int> Semester_ID { get; set; }
        public string Mentor_Email { get; set; }
        public Nullable<double> MentorPoint { get; set; }
        public string MentorComment { get; set; }
        public int Business_ID { get; set; }
        public Nullable<double> BusinessPoint { get; set; }
        public string BusinessComment { get; set; }
        public Nullable<int> InternshipTopic_ID { get; set; }
        public string Status { get; set; }
    
        public virtual BusinessUser BusinessUser { get; set; }
        public virtual InternshipTopic InternshipTopic { get; set; }
        public virtual Semester Semester { get; set; }
        public virtual VanLangUser VanLangUser { get; set; }
    }
}
