//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessConnectManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InternshipTopic
    {
        public int ID { get; set; }
        public string InternshipTopicName { get; set; }
        public string InternshipTopicGoals { get; set; }
        public string InternshipTopicDescription { get; set; }
    }
}
