//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessConnectManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOU
    {
        public int ID { get; set; }
        public string Business_ID { get; set; }
        public Nullable<System.DateTime> SignDay { get; set; }
        public string Signer { get; set; }
        public string ContactName { get; set; }
        public string ContactPhone { get; set; }
        public string EmailContact { get; set; }
    
        public virtual BusinessUser BusinessUser { get; set; }
    }
}
