//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessConnectManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class MOU
    {
        public int ID { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập mã doanh nghiệp.")]
        public string Business_ID { get; set; }

        public Nullable<System.DateTime> SignDay { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập tên người ký.")]
        public string Signer { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập tên người liên hệ.")]
        public string ContactName { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập số điện thoại người liên hệ.")]
        [DataType(DataType.PhoneNumber)]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage = "Số điện thoại này không hợp lệ.")]
        public string ContactPhone { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập email người liên hệ.")]
        [RegularExpression("^[a-zA-Z0-9_\\.-]+@([a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}$", ErrorMessage = "E-mail không hợp lệ.")]
        [EmailAddress(ErrorMessage = "E-mail không hợp lệ.")]
        public string EmailContact { get; set; }

        public virtual BusinessUser BusinessUser { get; set; }
    }
}
