//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessConnectManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int ID { get; set; }
        public string Mentor_Email { get; set; }
        public Nullable<int> Business_ID { get; set; }
        public string Title { get; set; }
        public string Message { get; set; }
        public string Date { get; set; }
        public Nullable<bool> IsRead { get; set; }
    
        public virtual BusinessUser BusinessUser { get; set; }
        public virtual VanLangUser VanLangUser { get; set; }
    }
}
