//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessConnectManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostPosition
    {
        public int Id { get; set; }
        public Nullable<int> Post_ID { get; set; }
        public Nullable<int> Position_ID { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual Position Position { get; set; }
    }
}
