//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessConnectManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Post
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Post()
        {
            this.Registrations = new HashSet<Registration>();
        }
    
        public int ID { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập tên tiêu đề.")]
        [RegularExpression(@"^.*\S.*$", ErrorMessage = "Vui lòng nhập tên tiêu đề.")]
        public string Title { get; set; }
        public string Email_ID { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> PostDay { get; set; }
        public Nullable<System.DateTime> ModifyDay { get; set; }
        public Nullable<int> Semester_ID { get; set; }
        public string PostImage { get; set; }
        public Nullable<int> Business_ID { get; set; }
    
        public virtual BusinessUser BusinessUser { get; set; }
        public virtual Semester Semester { get; set; }
        public virtual VanLangUser VanLangUser { get; set; }
        public virtual VanLangUser VanLangUser1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Registration> Registrations { get; set; }
    }
}
