//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessConnectManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        public int ID { get; set; }
        public string Email_VanLang { get; set; }
        public Nullable<int> Post_ID { get; set; }
        public Nullable<int> Semester_ID { get; set; }
        public string CV { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public Nullable<System.DateTime> RegistrationModify { get; set; }
        public int Business_ID { get; set; }
        public string InterviewResult { get; set; }
        public string InterviewResultComment { get; set; }
        public string StatusInternview { get; set; }
        public string StatusRegistration { get; set; }
        public string Comment { get; set; }
    
        public virtual BusinessUser BusinessUser { get; set; }
        public virtual Post Post { get; set; }
        public virtual Semester Semester { get; set; }
        public virtual VanLangUser VanLangUser { get; set; }
    }
}
