//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessConnectManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trainee
    {
        public int ID { get; set; }
        public string Mentor_Email { get; set; }
        public string Student_Email { get; set; }
        public Nullable<int> Semester_ID { get; set; }
    
        public virtual Semester Semester { get; set; }
        public virtual VanLangUser VanLangUser { get; set; }
        public virtual VanLangUser VanLangUser1 { get; set; }
    }
}
